Repository pagopa/pagopa-gpd-ingestion-manager, pull requests merged in 2024-11, with the labels that each got.

#2 feat: Update chart version to 5.9.0
  helm/Chart.lock
  helm/Chart.yaml
  helm/values-dev.yaml
Labels: patch, size/small

#4 fix: Add new field paymentOptionId to Transfer obj
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/gpd/ingestion/manager/entity/Transfer.java
Labels: patch, size/small

#3 fix: Updated logback dependencies
  pom.xml
Labels: patch, size/small

#7 fix: Integration tests
  integration-test/src/features/gpd_ingestion_manager.feature
  integration-test/src/step_definitions/gpd_ingestion_manager_step.js
  integration-test/src/step_definitions/pg_gpd_client.js
Labels: patch, size/small

#8 fix: Improve logs & fix null message redis
  .gitignore
  host.json
  test-utils/kafka-to-redis/kafka_event_hub_client.js
Labels: patch, size/small

#6 [PPANTT-170] feat: Performance tests
  .devops/code-review-pipelines.yml
  .devops/deploy-pipelines-aks.yml
  .devops/deploy-pipelines-standard.yml
  .devops/performance-test-pipelines.yml
  .github/workflows/code_review.yml
  performance-test/src/.env.dev
  performance-test/src/.env.uat
  performance-test/src/gpd_ingestion_test.js
  performance-test/src/modules/common.js
  performance-test/src/modules/pg_gpd_client.js
  performance-test/src/modules/redis_client.js
  performance-test/src/package.json
  performance-test/src/scripts/review_script.js
Labels: skip, size/large

#11 fix: Deploy GHA
  .github/workflows/deploy_with_github_runner.yml
  .github/workflows/release-deploy.yml
Labels: skip, size/small

#12 fix: Remove fullname overdrive helm
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: skip, size/small

#13 fix: Remove otel env helm
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
Labels: skip, size/small

#15 chore: Update initialDelaySeconds
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch

#16 fix: Removed double actuator dependency
  pom.xml
Labels: patch, size/small

#17 fix: Add serviceMonitor config to helm for monitoring
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small

#18 Update performance-test-pipelines.yml for Azure Pipelines
  .devops/performance-test-pipelines.yml
  .gitignore
  performance-test/src/load/DockerfileLoad
  performance-test/src/load/gpd_ingestion_test.js
  performance-test/src/modules/redis_client.js
  performance-test/src/package.json
  performance-test/src/review/DockerfileReview
  performance-test/src/review/review_script.js
  test-utils/docker-compose.yml
Labels: size/small

#19 fix: Change try catch inside for loop to prevent losing events
  src/main/java/it/gov/pagopa/gpd/ingestion/manager/events/producer/impl/IngestedPaymentOptionProducerImpl.java
  src/main/java/it/gov/pagopa/gpd/ingestion/manager/events/producer/impl/IngestedPaymentPositionProducerImpl.java
  src/main/java/it/gov/pagopa/gpd/ingestion/manager/events/producer/impl/IngestedTransferProducerImpl.java
  src/main/java/it/gov/pagopa/gpd/ingestion/manager/service/impl/IngestionServiceImpl.java
Labels: patch, size/large

#20 fix: Performance test eventhub connection string
  .devops/performance-test-pipelines.yml
Labels: skip, size/small
