Repository pagopa/pagopa-gpd-ingestion-manager, pull requests merged in 2024-12, with the labels that each got.

#22 fix: Integration test asserts
  integration-test/src/step_definitions/gpd_ingestion_manager_step.js
Labels: skip, size/small

#23 [PPANTT-221] fix: Filter null values from messages' lists
  src/main/java/it/gov/pagopa/gpd/ingestion/manager/service/impl/IngestionServiceImpl.java
Labels: patch, size/small

#14 feat: Update github runner for deploy GHA
  .github/workflows/deploy_with_github_runner.yml
Labels: skip, size/small

#24 chore: updated prod values for retries and log level
  helm/values-prod.yaml
Labels: skip, size/small

#25 feat: introduced placeholder and missing status
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  src/main/java/it/gov/pagopa/gpd/ingestion/manager/events/model/entity/enumeration/PaymentPositionStatus.java
  src/main/java/it/gov/pagopa/gpd/ingestion/manager/service/impl/IngestionServiceImpl.java
  src/main/resources/application.properties
  src/test/java/it/gov/pagopa/gpd/ingestion/manager/service/impl/IngestionServiceImplTest.java
  src/test/resources/application.properties
Labels: minor, size/small

#26 fix: introduced env var to disable kafka metrics
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: patch, size/small
