Repository pagopa/pagopa-gpd-ingestion-manager, pull requests merged in 2025-01, with the labels that each got.

#27 [PPANTT-216] feat: Workload Identity
  .github/workflows/deploy_with_github_runner.yml
  .identity/00_data.tf
  .identity/03_github_environment.tf
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: minor, size/small

#28 fix: deploy
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
Labels: skip, size/small

#29 fix: Deploy
  .github/workflows/deploy_with_github_runner.yml
  helm/Chart.yaml
  helm/values-dev.yaml
  helm/values-prod.yaml
  helm/values-uat.yaml
  pom.xml
Labels: patch, size/small
